name: Benchmarking

on:
  push:
    branches:
      - master

  pull_request:

  # allow manually starting this workflow
  workflow_dispatch:

jobs:
  industrial_ci:
    name: ${{ matrix.env.CI_NAME }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env:
          - {CI_NAME: Focal-Benchmark}
    steps:
      - uses: actions/checkout@v2

      - name: Prepare ccache timestamp
        id: ccache_cache_timestamp
        shell: cmake -P {0}
        run: |
          string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
          message("::set-output name=timestamp::${current_date}")

      - name: ccache cache files
        uses: actions/cache@v1.1.0
        with:
          path: ${{ matrix.env.CI_NAME }}/.ccache
          key: ${{ matrix.env.CI_NAME }}-ccache-${{ steps.ccache_cache_timestamp.outputs.timestamp }}
          restore-keys: |
            ${{ matrix.env.CI_NAME }}-ccache-

      - name: Generate fake benchmark
        run: |
          touch ${{ github.workspace }}/benchmarks/tesseract-benchmark_result.json

      - name: Store Bullet Discrete, FCL Discrete and Environment benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: C++ Benchmark
          tool: 'googlecpp'
          output-file-path: ${{ github.workspace }}/benchmarks/tesseract-benchmark_result.json
          benchmark-data-dir-path: tesseract/benchmark
          gh-repository: github.com/marip8/tesseract_docs
          auto-push: false
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: false
          alert-comment-cc-users: '@Levi-Armstrong'
          max-items-in-chart: 20

      - name: Push benchmark result
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.DOCS_DEPLOY_KEY }}
        with:
          source-directory: .
          destination-github-username: marip8
          destination-repository-name: tesseract_docs
          target-branch: gh-pages
